services:
  no-EA-no-freeze:
    profiles: ["experiments"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: no-EA-no-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --config_file config/config.yaml --ea no-alignment --freeze no-freeze --num_exp exp_hybrid --dataset ${DATASET}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu ]

  yes-EA-no-freeze:
    profiles: ["experiments"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: yes-EA-no-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --config_file config/config.yaml --ea alignment --freeze no-freeze --num_exp exp_hybrid --dataset ${DATASET}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [ gpu ]

  no-EA-yes-freeze:
    profiles: ["experiments"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: no-EA-yes-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --config_file config/config.yaml --ea no-alignment --freeze freeze --num_exp exp_hybrid --dataset ${DATASET}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  yes-EA-yes-freeze:
    profiles: ["experiments"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: yes-EA-yes-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --config_file config/config.yaml --ea alignment --freeze freeze --num_exp exp_hybrid --dataset ${DATASET}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  test-valid:
    profiles: ["debug"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: debug-yes-EA-yes-freeze
    command: "python src/Bruna/domain_adapt_exp1.py --config_file config/config.yaml --ea alignment --freeze freeze --num_exp exp_hybrid --dataset ${DATASET}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  shared-test:
    profiles: ["shared"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: test
    command: "python src/Bruna/domain_adapt_shared_exp.py --config_file config/config.yaml --ea no-alignment --freeze no-freeze --num_exp exp_shared --dataset ${DATASET}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [ gpu ]

  jupyter:
    profiles: ["jupyter"]
    #user: "0:0"
    extends:
      file: base.yml
      service: base-experiment
    container_name: jupyter-host
    command: "jupyter notebook --no-browser"
    ports:
      - "9999:8888"
    environment:
      JUPYTER_TOKEN: "docker"

  shell:
    profiles: ["shell"]
    extends:
      file: base.yml
      service: base-experiment
    container_name: debug-shell
    command: ["/bin/bash"]
    stdin_open: true

volumes:
  moabb-datasets:
    external: true