seed: 42
train:
    num_workers: 10
    run_report: '/mnt/beegfs/home/aristimunha/bruna/EEG_EA-Domain-Adap/output/'
    n_epochs: 200
    patience: 150
    weight_decay: 1e-5
    batch_size: 8
    lr: 0.000625
    valid_split: 0.2
    experiment_name: 'indiv_batch8'
model:
    drop_prob: 0.5
    final_conv_length: 'auto'
dataset:
    path: '/mnt/beegfs/home/aristimunha/moabb/mne_data'