seed: 42
train:
    num_workers: 10
    run_report: '/mnt/beegfs/home/aristimunha/bruna/EEG_EA-Domain-Adap/output/'
    n_epochs: 1000
    patience: 250
    weight_decay: 0
    batch_size: 64
    lr: 0.000525
    valid_split: 0.2
    experiment_name: 'shared_m3_250'
ft:
    n_epochs: 600
    lr: 0.000125
    patience: 250
    weight_decay: 0
model:
    type: 'ShallowFBCSPNet'
    drop_prob: 0.4
    final_conv_length: 'auto'
dataset:
    path: '/mnt/beegfs/projects/moabb/mne_data'