seed: 42
train:
    num_workers: 10
    run_report: '/mnt/beegfs/home/aristimunha/bruna/EEG_EA-Domain-Adap/output/'
    n_epochs: 1000
    patience: 200
    weight_decay: 1e-5
    batch_size: 64
    lr: 0.000625
    valid_split: 0.2
    experiment_name: 'indiv_1000epochs_p200'
model:
    drop_prob: 0.5
    final_conv_length: 'auto'
dataset:
    path: '/mnt/beegfs/projects/moabb/mne_data'