seed: 42
train:
    num_workers: 10
    run_report: '/mnt/beegfs/home/aristimunha/bruna/EEG_EA-Domain-Adap/output/'
    n_epochs: 1000
    patience: 250
    weight_decay: 1e-5
    batch_size: 64
    lr: 0.00125
    valid_split: 0.2
    experiment_name: 'indiv_m1_final'
ft:
    n_epochs: 600
    lr: 0.0000825
    patience: 150
    weight_decay: 1e-5
model:
    type: 'EEGNetv4'
    drop_prob: 0.35
    final_conv_length: 'auto'
dataset:
    path: '/mnt/beegfs/projects/moabb/mne_data'
