seed: 42
train:
    num_workers: 10
    run_report: '/mnt/beegfs/home/aristimunha/bruna/EEG_EA-Domain-Adap/output/'
    n_epochs: 1000
    patience: 150
    weight_decay: 1e-5
    batch_size: 64
    lr: 0.000625
    valid_split: 0.2
    experiment_name: 'shared_m1_wd0'
ft:
    n_epochs: 600
    weight_decay: 1e-5
    patience: 150
    lr: 0.000625
model:
    type: 'EEGNetv4'
    drop_prob: 0.3
    final_conv_length: 'auto'
dataset:
    path: '/mnt/beegfs/projects/moabb/mne_data'
