seed: 42
train:
    num_workers: 10
    run_report: '/mnt/beegfs/home/aristimunha/bruna/EEG_EA-Domain-Adap/output/'
    n_epochs: 400
    n_epochs_ft: 400
    patience: 150
    weight_decay: 0.0002
    batch_size: 64
    lr: 0.0004
    valid_split: 0.2
    experiment_name: 'shared_m2'
model:
    type: 'Deep4Net'
    drop_prob: 0.4
    final_conv_length: 'auto'
dataset:
    path: '/mnt/beegfs/projects/moabb/mne_data'
