seed: 50
train:
    num_workers: 10
    run_report: '/workspace/outputs'
    n_epochs: 1000
    patience: 400
    weight_decay: 0
    batch_size: 64
    lr: 0.01
    valid_split: 0.2
    experiment_name: 'hybrid-sch-deep'
    model_arch: 'ShallowNet'
model:
    drop_prob: 0.4
    final_conv_length: 'auto'

dataset:
    path: "/workspace/datasets/"