seed: 23
train:
    num_workers: 10
    run_report: '/project/outputs'
    n_epochs: 400
    patience: 150
    weight_decay: 0
    batch_size: 64
    lr: 0.05
    valid_split: 0.2
    experiment_name: 'exp5_comp'
model:
    drop_prob: 0.5
    final_conv_length: 'auto'
dataset:
    path: "/project/dataset/"