seed: 23
train:
    num_workers: 10
    run_report: '/workspace/outputs'
    n_epochs: 100
    patience: 300
    weight_decay: 0
    batch_size: 9
    lr: 0.005
    valid_split: 0.1
    experiment_name: 'exp5_comp'
model:
    drop_prob: 0.3
    final_conv_length: 'auto'

dataset:
    path: "/workspace/datasets/"